package br.com.musicas.opus13.nina;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=11000"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void intro() {
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
	}

	@Override
	public void estrofe() {
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s"), 1);		

		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);	

		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i Ri [LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i Ri [ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i [CRASH_CYMBAL_2]i"), 1);				
	}

	@Override
	public void solo() {
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[SIDE_STICK]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i"), 1);		
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s"), 1);		

		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);	

		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CLOSED_HI_HAT]i"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]i+[LOW_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[HIGH_TOM]i+[ACOUSTIC_BASS_DRUM]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [OPEN_HI_HAT]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i+[ACOUSTIC_BASS_DRUM]i [OPEN_HI_HAT]i"), 1);				
		partitura.add(new Pattern("[ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s Ri [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s Ri [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s Ri [HIGH_TOM]i+[LOW_TOM]i [HIGH_TOM]i+[LOW_TOM]i"), 1);				
	}

	@Override
	public void fim() {
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_1]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i"), 1);		
		partitura.add(new Pattern("[RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_BASS_DRUM]i [RIDE_CYMBAL_2]i+[ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
	}
		
}
