package br.com.musicas.opus06.morrisonhotel;

import java.util.Random;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=10000"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void estrofe() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_1]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern(trocaVirada()), 1);
	}

	@Override
	public void refrao() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern(trocaVirada()), 1);
	}

	@Override
	public void solo() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_1]i "
						+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern(trocaVirada()), 1);
	}
	
	@Override
	public void intro() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern(trocaVirada()), 1);
	}
	
	@Override
	public void fim() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
				+ "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_2]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_2]q Ri [SIDE_STICK]i [SIDE_STICK]i [SIDE_STICK]i"), 1);
	}

	private String trocaVirada(){
		String escolhas[] = { 
							  "[LOW_TOM]i        Ri         [HIGH_FLOOR_TOM]i [HI_MID_TOM]i     "
							+ "[HIGH_TOM]i       Ri          [ACOUSTIC_SNARE]i      [CRASH_CYMBAL_1]i ",
							  "[LOW_FLOOR_TOM]i  [LOW_TOM]i [HIGH_FLOOR_TOM]i [HI_MID_TOM]i     "
							+ "[HIGH_TOM]i       [HIGH_TOM]i [ACOUSTIC_SNARE]i      [CRASH_CYMBAL_2]i ",
							  "[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri         [ACOUSTIC_SNARE]i "
							+ "[ACOUSTIC_SNARE]i Ri          [LOW_TOM]i+[HIGH_TOM]i [CRASH_CYMBAL_1]i ",
							  "[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i "
							+ "[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_2]q",							 
							  "[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i "
							+ "[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [CRASH_CYMBAL_2]i"
							};
						
		Random rand = new Random();
		
		return escolhas[rand.nextInt(escolhas.length)];
	}
	
}
