package br.com.musicas.opus17.timetodie;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=10000"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void intro() {
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i "), 1);

		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_2]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_2]i "), 1);
	}

	@Override
	public void estrofe() {
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i "), 1);

		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_2]i "), 1);

		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i "), 1);

		partitura.add(new Pattern("[CRASH_CYMBAL_2]q Rq"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("Rq [CRASH_CYMBAL_2]q"), 1);
	}

	@Override
	public void refrao() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [RIDE_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [RIDE_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [RIDE_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [RIDE_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [CRASH_CYMBAL_2]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [CRASH_CYMBAL_2]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i"), 1);
	}
		
	@Override
	public void solo() {
	}

	@Override
	public void fim() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [RIDE_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [CRASH_CYMBAL_2]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q+[RIDE_CYMBAL_1]q [ACOUSTIC_SNARE]q+[RIDE_CYMBAL_1]q [CRASH_CYMBAL_2]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[HIGH_TOM]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i [ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[LOW_TOM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_1]i "
								+ "[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[OPEN_HI_HAT]i+[ACOUSTIC_SNARE]i [ACOUSTIC_BASS_DRUM]i+[HIGH_TOM]i+[LOW_TOM]i+[CRASH_CYMBAL_2]i"), 1);
	}

}
