package br.com.musicas.opus04.Iloveyou;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=11000"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void intro() {
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s"), 1);		
	}

	@Override
	public void refrao1() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);
	}

	@Override
	public void estrofe1() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);
	}

	@Override
	public void transposicao() {
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [CRASH_CYMBAL_2]i"), 1);		
	}

	@Override
	public void refrao2() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);
	}

	@Override
	public void estrofe2() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_2]i [RIDE_CYMBAL_2]i [ACOUSTIC_SNARE]i+[RIDE_CYMBAL_2]i [CRASH_CYMBAL_2]i"), 1);

		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [CRASH_CYMBAL_2]i"), 1);
	}
		
	@Override
	public void fim() {
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i Ri"), 1);
		partitura.add(new Pattern("[CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q [CLOSED_HI_HAT]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]w+[CRASH_CYMBAL_2]w"), 1);
	}

}
