package br.com.musicas.opus12.todayyourlove;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=8600"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void refrao() {
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]qi+[CRASH_CYMBAL_1]qi"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [ACOUSTIC_BASS_DRUM]qi+[CRASH_CYMBAL_2]qi"), 1);
	}

	@Override
	public void estrofe() {
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_2]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i"), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i+[RIDE_CYMBAL_1]i [RIDE_CYMBAL_1]i [ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[RIDE_CYMBAL_1]i [CRASH_CYMBAL_2]i"), 1);
	}

	@Override
	public void fim() {
	}

	@Override
	public void ponte() {
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}
		
}
