package br.com.musicas.opus07.iwontbeyourlover;

import org.jfugue.Pattern;


public class Bateria extends Estrutura{

	@Override
	public void inicio() {
		partitura.add(new Pattern("V9 X[Volume]=12000"));
		partitura.add(new Pattern("[SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q [SIDE_STICK]q"), 1);		
	}

	@Override
	public void estrofe() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
	}

	@Override
	public void refrao() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[OPEN_HI_HAT]q+[CRASH_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[OPEN_HI_HAT]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_1]i [OPEN_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[OPEN_HI_HAT]i [ACOUSTIC_SNARE]i+[CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[OPEN_HI_HAT]q+[CRASH_CYMBAL_1]q "), 1);
	}

	@Override
	public void ponte() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_2]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_2]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[LOW_TOM]i [LOW_TOM]i [HIGH_TOM]i [HIGH_TOM]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_2]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_1]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q+[CRASH_CYMBAL_2]q [ACOUSTIC_BASS_DRUM]q"), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]q [ACOUSTIC_BASS_DRUM]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]q Rq "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i [ACOUSTIC_SNARE]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_SNARE]q [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s [ACOUSTIC_SNARE]s "), 1);
	}
		
	@Override
	public void fim() {
	}

	@Override
	public void solo() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
	}

	@Override
	public void intro() {
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CLOSED_HI_HAT]i [ACOUSTIC_SNARE]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_1]i "), 1);
		partitura.add(new Pattern("[ACOUSTIC_BASS_DRUM]i+[ACOUSTIC_BASS_DRUM]i+[CLOSED_HI_HAT]i [CRASH_CYMBAL_2]i [ACOUSTIC_SNARE]q+[CRASH_CYMBAL_1]q "), 1);
	}
	
}
